changes es
KMPARDS/explorer pull request #74
Opened 2020-11-20 11:49 UTC by riya249

2020-11-20 13:16 UTC, maheshrapelli141 requested changes
Check the line 190 in Block.js page

2020-11-20 13:16 UTC, maheshrapelli141 commented on src/Containers/Blocks/Blocks.js
> +                                <i>Time Remaining for  Next NRT released...</i>
Here, it should show nrt timer instead of text

2020-11-20 13:56 UTC, TarunBaur approved these changes

2020-11-21 13:32 UTC, TarunBaur approved these changes

2020-11-21 14:02 UTC, maheshrapelli141 approved these changes

2020-11-21 14:02 UTC, merged